"""created company

Revision ID: 64e53a00b7b9
Revises: 38f73289aeb9
Create Date: 2023-12-13 15:29:49.529319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64e53a00b7b9"
down_revision: Union[str, None] = "38f73289aeb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("address", sa.String(length=100), nullable=False),
        sa.Column("people", sa.Integer(), nullable=True),
        sa.Column("hunt_count", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=7), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("ticker"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company")
    # ### end Alembic commands ###
